# Generated by Django 3.1.1 on 2021-04-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('ReferralEarning', models.CharField(max_length=50)),
                ('ActivitiesEarning', models.CharField(max_length=50)),
                ('Package', models.CharField(max_length=50)),
                ('NextWithdraw', models.DateField()),
                ('UnpaidReferral', models.CharField(max_length=20)),
                ('PaidReferral', models.CharField(max_length=20)),
                ('CurrentReferral', models.CharField(max_length=20)),
                ('TotalReferral', models.CharField(max_length=20)),
                ('Cycles', models.CharField(max_length=20)),
                ('PreviousReferral', models.CharField(max_length=20)),
                ('AvailableEarning', models.CharField(max_length=20)),
            ],
        ),
    ]
